#!/bin/bash

# SPDX-FileCopyrightText: Copyright 2024-2026 Arm Limited and affiliates.
#
# SPDX-License-Identifier: Apache-2.0

# Note that this script intentionally has no options. It builds *the* torchao
# Tool-Solutions, of which there is only one type

set -eux -o pipefail

PYTHON_VERSION="3.12"

# Specify DOCKER_IMAGE_MIRROR if you want to use a mirror of hub.docker.com
IMAGE_NAME="${DOCKER_IMAGE_MIRROR:-}pytorch/manylinux2_28_aarch64-builder:cpu-aarch64-69d4c1f80b5e7da224d4f9c2170ef100e75dfe03"
TORCH_BUILD_CONTAINER_ID_FILE="${PWD}/.torch_ao_build_container_id"

TEST_VENV=aarch64_env_test_torch_ao

TORCH_AO_HOST_DIR="${PWD}/ao"

TORCH_AO_ROOT=/ao

if [ -f "$TORCH_BUILD_CONTAINER_ID_FILE" ]; then
    TORCH_BUILD_CONTAINER=$(cat $TORCH_BUILD_CONTAINER_ID_FILE)
    echo "Found an existing torch build container id: $TORCH_BUILD_CONTAINER"
else
    TORCH_BUILD_CONTAINER=""
    echo "Did not find torch build container id in $(readlink -f $TORCH_BUILD_CONTAINER_ID_FILE), we will create one later"
fi

if ! docker container inspect $TORCH_BUILD_CONTAINER >/dev/null 2>&1 ; then

    TORCH_BUILD_CONTAINER=$(docker run -t -d \
        -e BINARY_ENV_FILE=/tmp/env \
        -e BUILD_ENVIRONMENT=linux-aarch64-binary-manywheel \
        -e DESIRED_CUDA=cpu \
        -e DESIRED_PYTHON=$PYTHON_VERSION \
        -e GITHUB_ACTIONS=0 \
        -e GPU_ARCH_TYPE=cpu-aarch64 \
        -e PACKAGE_TYPE=manywheel \
        -e TORCH_AO_ROOT="${TORCH_AO_ROOT}" \
        -e SKIP_ALL_TESTS=1 \
        -e TEST_VENV="${TEST_VENV}" \
        -v "${TORCH_AO_HOST_DIR}:${TORCH_AO_ROOT}" \
        -w / \
        "${IMAGE_NAME}")

    # The Docker image comes with a copy of ACL, but we want to build against whichever
    # version is compatible with the pip-installed torch (which ships its own copy of ACL),
    # so we remove the existing copy here
    docker exec -t $TORCH_BUILD_CONTAINER bash -c "cd / && rm -rf acl/"

    docker exec -t $TORCH_BUILD_CONTAINER bash -c "python${PYTHON_VERSION} -m venv $TEST_VENV"
    docker exec -t $TORCH_BUILD_CONTAINER bash -c "source $TEST_VENV/bin/activate && pip install typing_extensions torch wheel numpy --no-deps"

    echo "Storing torch build container id in $TORCH_BUILD_CONTAINER_ID_FILE for reuse: $TORCH_BUILD_CONTAINER"
    echo $TORCH_BUILD_CONTAINER > "$TORCH_BUILD_CONTAINER_ID_FILE"
else
    docker restart $TORCH_BUILD_CONTAINER
fi

# Clean up any old builds
docker exec -t $TORCH_BUILD_CONTAINER bash -c "rm -rf ${TORCH_AO_ROOT}/build ${TORCH_AO_ROOT}/dist"

# Build
docker exec -t $TORCH_BUILD_CONTAINER bash -c \
  "source ${TEST_VENV}/bin/activate && \
   cd ${TORCH_AO_ROOT} && \
   python${PYTHON_VERSION} -m pip install setuptools build && \
   python${PYTHON_VERSION} -m build --wheel --no-isolation"

# directories generated by the docker container are owned by root, so transfer ownership to user
docker exec $TORCH_BUILD_CONTAINER chown -R "$(id -u)":"$(id -g)" "${TORCH_AO_ROOT}"
