# *******************************************************************************
# Copyright 2021  Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# *******************************************************************************

description: >-
  resnet50-v1.5 is a TensorFlow implementation of ResNet-50 - an image classification model
  pretrained on the ImageNet dataset. For details on how this model was trained please see
  <https://github.com/mlcommons/training/tree/master/image_classification> for more information
model:
  - name: resnet_v1-50.pb
    source: https://zenodo.org/record/2535873/files/resnet50_v1.pb
    labels: https://s3.amazonaws.com/deep-learning-models/image-models/imagenet_class_index.json
arguments:
  - input_shape: [1,224,224,3]
    input: input_tensor
    output: softmax_tensor