/*
 * Copyright (c) 2021 Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//---------------------------------------------
// This file was autogenerated by the script
// convert_images_to_cpp.sh
// Do not edit
//---------------------------------------------


#include "images.hpp"


static const char *image_names[] = {
    "tree",
    "POV_cat",
    "person_male_man_men",
    "JP_Kyoto_kimono",
};

static const unsigned char *image_pointers[] = {
    tree,
    POV_cat,
    person_male_man_men,
    JP_Kyoto_kimono,
};


const char* get_image_name(const uint32_t fileindex)
{
    if (fileindex < NUMBER_OF_IMAGES) {
        return image_names[fileindex];
    }
    return nullptr;
}

const unsigned char* get_image_pointer(const uint32_t fileindex)
{
    if (fileindex < NUMBER_OF_IMAGES) {
        return image_pointers[fileindex];
    }
    return nullptr;
}

uint32_t get_image_len(const uint32_t fileindex)
{
    if (fileindex < NUMBER_OF_IMAGES) {
        return IMAGE_DATA_SIZE;
    }
    return 0;
}
