[ -z "$PS1" ] && return

export PS1="\[\e[34m\]fvp-docker\[\e[m\] \[\e[32m\]\w\[\e[m\] > "
export TERM=xterm-256color
alias grep="grep --color=auto"
alias ls="ls --color=auto"

echo -e "\e[1;36m"
cat<<FVP
Arm Corstone SSE 300 FVP Docker Container
FVP
echo -e "\e[0;33m"

if [[ $EUID -eq 0 ]]; then
  cat <<WARN
You are running this container as root
WARN
else
  cat <<EXPL
You are running this container as user with ID $(id -u) and group $(id -g)
EXPL
fi

# Turn off colors
echo -e "\e[m"
