# SPDX-FileCopyrightText: Copyright 2025, 2026 Arm Limited and affiliates.
#
# SPDX-License-Identifier: Apache-2.0

name: "Build and test PyTorch"

#* To avoid duplicate jobs running when both push and PR is satisfied, we use this:
#* https://github.com/orgs/community/discussions/26940#discussioncomment-5686753
on:
  push:
    branches: [main]
    paths:
      - ".github/**"
      - "ML-Frameworks/pytorch-aarch64/**"
      - "ML-Frameworks/utils/**"
      # Exclusions (must come after the includes):
      - "!ML-Frameworks/pytorch-aarch64/CHANGELOG.md"
      - "!ML-Frameworks/pytorch-aarch64/README.md"
      - "!ML-Frameworks/pytorch-aarch64/welcome.txt"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/**"
      - "ML-Frameworks/pytorch-aarch64/**"
      - "ML-Frameworks/utils/**"
      # Exclusions (must come after the includes):
      - "!ML-Frameworks/pytorch-aarch64/CHANGELOG.md"
      - "!ML-Frameworks/pytorch-aarch64/README.md"
      - "!ML-Frameworks/pytorch-aarch64/welcome.txt"
  schedule:
    #* minute (0-59) hour (0-23) day (1-31) month (1-12)  day of the week (0 - 6)
    #* cron jobs run on the default (main) branch.
    #* set to run at 5am UCT
    - cron: "0 5 * * *"
  #* allow manual trigger of workflow when needed.
  workflow_dispatch:

#* Stop stale workflows when pull requests are updated: https://stackoverflow.com/a/70972844
#* Does not apply to the main branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# Declare default permissions as read only.
permissions: read-all

jobs:
  run-c6g:
    name: "c6g - build & test"
    uses: ./.github/workflows/_pytorch-single-platform.yml
    with:
      target_name: c6g
      runner_label: ah-ubuntu_22_04-c6g_8x-100
      onednn_fpmath_modes_json: '["FP32"]'
    secrets: inherit

  run-c7g:
    name: "c7g - build & test"
    uses: ./.github/workflows/_pytorch-single-platform.yml
    with:
      target_name: c7g
      runner_label: ah-ubuntu_24_04-c7g_8x-100
      onednn_fpmath_modes_json: '["FP32","BF16"]'
    secrets: inherit

  run-c8g:
    name: "c8g - build & test"
    uses: ./.github/workflows/_pytorch-single-platform.yml
    with:
      target_name: c8g
      runner_label: ah-ubuntu_24_04-c8g_8x
      onednn_fpmath_modes_json: '["FP32","BF16"]'
    secrets: inherit
