# *******************************************************************************
# Copyright 2025 Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# *******************************************************************************

name: "Build and test Tensorflow"

#* To avoid duplicate jobs running when both push and PR is satisfied, we use this:
#* https://github.com/orgs/community/discussions/26940#discussioncomment-5686753
on:
  workflow_call:
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  build-and-test:
    strategy:
      matrix:
        config: [
          { name: c7g, label: ah-ubuntu_22_04-c7g_8x-100 } # Metal instance required as 4x large is not big enough
        ]

    runs-on: ${{ matrix.config.label }}
    steps:
      - name: Checkout Tool-Solutions
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: Tool-Solutions
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Build Tool-Solutions Tensorflow
        working-directory: ${{ github.workspace }}/Tool-Solutions/ML-Frameworks/tensorflow-aarch64
        run: ${{ github.workspace }}/Tool-Solutions/ML-Frameworks/tensorflow-aarch64/build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run smoke tests
        run: docker run --rm toolsolutions-tensorflow:latest ./test_examples.sh

      - name: Run unit tests
        run: docker run --rm toolsolutions-tensorflow:latest ./run_unit_tests.sh
